Raptor.Presentation/Raptor.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Raptor.Core.Helpers;
using Raptor.Data.Models.Logging;
using Raptor.Data.Models.Users;
using Raptor.Services.Authentication;
using Raptor.Services.Helpers;
using Raptor.Services.Logging;
using Raptor.Services.Users;
using Raptor.Web.ViewModels;
using System;

namespace Raptor.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        private readonly IUserRegisterationService _userRegisterationService;
        private readonly IUserAuthenticationService _authService;
        private readonly ICustomerActivityService _activityService;
        private readonly ILogService _logService;
        private readonly IWorkContext _workContext;

        public AuthController(IUserService userService, IUserRegisterationService userRegisterationService, IUserAuthenticationService authService, ICustomerActivityService activityService, ILogService logService, IWorkContext workContext) {
            _userService = userService;
            _userRegisterationService = userRegisterationService;
            _authService = authService;
            _activityService = activityService;
            _logService = logService;
            _workContext = workContext;
        }

        public IActionResult Index() {
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login(string returnUrl = "") {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");

            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginViewModel model, string returnUrl = "") {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");

            if (!ModelState.IsValid) return View(model);

            var isEmailAddress = CommonHelper.IsValidEmail(model.UsernameOrEmailAddress);

            var userExists = isEmailAddress
                ? _userService.CheckIfUserExistsByEmail(model.UsernameOrEmailAddress)
                : _userService.CheckIfUserExistsByUsername(model.UsernameOrEmailAddress);

            if (!userExists) {
                ModelState.AddModelError("", "No user found for the specified username / email address.");
                return View(model);
            }

            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            var loginResult = _userRegisterationService.ValidateUser(model.UsernameOrEmailAddress, model.Password);
            switch (loginResult) {
                case UserLoginResults.Deleted:
                case UserLoginResults.UserNotExists:
                case UserLoginResults.NotActive:
                    ModelState.AddModelError("", "No user found for the specified username / email address.");
                    break;

                case UserLoginResults.WrongPassword:
                    ModelState.AddModelError("", "Incorrect password, please try again.");
                    break;

                case UserLoginResults.Successful:
                    _authService.SignIn(model.UsernameOrEmailAddress);
                    if (string.IsNullOrEmpty(returnUrl)) return RedirectToAction("Index", "Home");
                    return Redirect(returnUrl);
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Logout() {
            _authService.SignOut();
            _workContext.CurrentUser = null;
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult ForgotPassword() {
            return View();
        }

        [HttpPost]
        public IActionResult ForgotPassword(ForgotPasswordViewModel model) {
            if (!ModelState.IsValid) return View(model);

            try {
                var user = _userService.GetUserByEmail(model.EmailAddress);
                if (user != null) {
                    _userService.CreateForgotPasswordRequest(user.BusinessEntityId);
                    ViewBag.Status = "OK";
                    ViewBag.Message = "Please check your email for instructions on how to reset your password";
                }
            }
            catch (Exception ex) {
                ModelState.AddModelError("", ex.Message);
                _logService.InsertLog(LogLevel.Error, ex.Message, ex.ToString());
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult ResetPassword(string link) {
            var forgotPasswordRequest = _userService.ValidateForgotPasswordRequest(link);
            if (string.IsNullOrEmpty(link) || !forgotPasswordRequest) return RedirectToAction("Login");

            ViewBag.Link = link;
            return View("ResetPassword");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ResetPassword(ResetPasswordViewModel model) {
            if (!ModelState.IsValid) return View(model);

            try {
                var forgotPasswordRequest = _userService.GetForgotPasswordRequest(model.Link);
                var user = _userService.GetUserById(forgotPasswordRequest.BusinessEntityId);

                _userService.UpdatePassword(user.EmailAddress, model.Password);

                ViewBag.Status = "OK";
                ViewBag.Message = "Your password has been updated";
            }
            catch (Exception ex) {
                ModelState.AddModelError("", ex.Message);
                _logService.InsertLog(LogLevel.Error, ex.Message, ex.ToString());
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Register() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterViewModel model) {
            if (!ModelState.IsValid) return View(model);

            try {
                var userRegistrationResult = _userRegisterationService.Register(model.FirstName, model.LastName, model.EmailAddress, model.Username, model.Password);

                if (userRegistrationResult.Success) {
                    ViewBag.Status = "OK";
                    ViewBag.Message = "Your account has been successfully created!";
                }
                else {
                    foreach (var error in userRegistrationResult.Errors) {
                        ModelState.AddModelError("", error);
                    }
                }
            }
            catch (Exception ex) {
                ModelState.AddModelError("", ex.Message);
                _logService.InsertLog(LogLevel.Error, ex.Message, ex.ToString());
            }

            return View(model);
        }
    }
}

Raptor.Presentation/Raptor.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Raptor.Services.Blog;
using Raptor.Web.Models;

namespace Raptor.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly string _blogPostsListsView = "BlogPostsList";
        private readonly IBlogService _blogService;

        public BlogController(IBlogService blogService) {
            _blogService = blogService;
        }

        public IActionResult Index() {
            var model = new BlogListViewModel() {
                RecentPosts = _blogService.GetBlogPosts(mostRecentCount: 3).ToList(),
                AllPosts = _blogService.GetBlogPosts().ToList(),
                Categories = _blogService.GetBlogPostCategories().ToList(),
                Category = "All"
            };

            return View(_blogPostsListsView, model);
        }

        [Route("blog/category/{slug}")]
        public IActionResult BlogPostsByCategory(string slug) {
            var category = _blogService.GetBlogPostCategoryBySlug(slug);

            if (category == null) {
                return RedirectToAction("Index");
            }

            var model = new BlogListViewModel()
            {
                RecentPosts = _blogService.GetBlogPosts(mostRecentCount: 3).ToList(),
                AllPosts = _blogService.GetBlogPosts(categoryId: category.PostCategoryId).ToList(),
                Categories = _blogService.GetBlogPostCategories(),
                Category = category.Name
            };

            return View(_blogPostsListsView, model);
        }
    }
}

Raptor.Presentation/Raptor.Web/Views/Shared/_AdminBar.cshtml
@inject IWorkContext WorkContext
@model string

<div id="adminbar">
    <ul>
        <li>
            <a href="#">
                <img src="~/admin-theme/assets/img/raptor-logo.png" alt="RaptorCMS" class="raptor-logo" />
            </a>
        </li>
        <li>
            @if (Model == "home")
            {
                <a href="@Url.Action("Index", "Home", new { area = "" })">
                    <i class="fa fa-home"></i>
                    <span style="margin-left: 7px;">
                        @if (string.IsNullOrEmpty(ViewBag.SiteTitle)) {
                            <span>RaptorCMS</span>
                        }
                        else {
                            <span>@ViewBag.Title</span>
                        }
                        | Main Website
                    </span>
                </a>
            }
            else if (Model == "admin" ) 
            { 
                <a href="@Url.Action("Index", "Home", new { area = "admin" })">
                    <i class="fa fa-tachometer"></i>
                    <span style="margin-left: 7px;">@ViewBag.SiteTitle | Admin</span>
                </a>
            }
        </li>
        <li>
            <a href="@Url.Action("Create", "Blog", new { area = "admin" })">
                <i class="fa fa-plus"></i>
                <span style="margin-left: 7px;">New</span>
            </a>
        </li>
    </ul>

    <ul  style="float: right; text-align: right;">
        <li>
            @if (WorkContext.CurrentUser != null) {
                <a href="@Url.Action("Settings", "Account", new { area = "admin" })">
                    <i class="fa fa-user"></i>
                    <span style="margin-left: 7px;">Hello, @WorkContext.CurrentUser.LastName</span>
                </a>
            }
            else {
                <a href="@Url.Action("Login", "Auth")">
                    <i class="fa fa-key"></i>
                    <span style="margin-left: 7px;">Login / Register</span>
                </a>
            }
        </li>
    </ul>
</div>

Raptor.Presentation/Raptor.Web/Views/Shared/_Layout.cshtml
@inject ISettingService settings
@{
    ViewBag.SiteTitle = settings.GetSettingByKey(SettingsConstants.SiteName).Value;
}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>@ViewBag.Title | @ViewBag.SiteTitle</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,700" rel="stylesheet">

    <link rel="stylesheet" href="~/themes/balita/css/bootstrap.css">
    <link rel="stylesheet" href="~/themes/balita/css/animate.css">
    <link rel="stylesheet" href="~/themes/balita/css/owl.carousel.min.css">

    <link rel="stylesheet" href="~/themes/balita/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/themes/balita/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/themes/balita/fonts/flaticon/font/flaticon.css">

    <link asp-append-version="true" rel="stylesheet" href="~/themes/balita/css/style.css">
    <link asp-append-version="true" href="~/admin-theme/assets/css/admin.css" rel="stylesheet" />
</head>
<body>

    <!-- HEADER -->
    @Html.Partial("_AdminBar", "admin")
    <header role="banner">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-9 social">
                        <a href="@settings.GetSettingByKey(SettingsConstants.TwitterUrl).Value"><span class="fa fa-twitter"></span></a>
                        <a href="@settings.GetSettingByKey(SettingsConstants.FacebookUrl).Value"><span class="fa fa-facebook"></span></a>
                        <a href="@settings.GetSettingByKey(SettingsConstants.InstagramUrl).Value"><span class="fa fa-instagram"></span></a>
                        <a href="@settings.GetSettingByKey(SettingsConstants.YoutubeUrl).Value"><span class="fa fa-youtube-play"></span></a>
                    </div>
                    <div class="col-3 search-top">
                        <!-- <a href="#"><span class="fa fa-search"></span></a> -->
                        <form asp-controller="Home" asp-action="Search" class="search-top-form">
                            <span class="icon fa fa-search"></span>
                            <input type="text" id="query" name="query" placeholder="Type keyword to search...">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="container logo-wrap">
            <div class="row pt-5">
                <div class="col-12 text-center">
                    <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
                    <h1 class="site-logo"><a href="index.html">@settings.GetSettingByKey(SettingsConstants.SiteName).Value</a></h1>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-md  navbar-light bg-light">
            <div class="container">


                <div class="collapse navbar-collapse" id="navbarMenu">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a id="link-home" class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="link-blog" class="nav-link" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a id="link-contact" class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- /HEADER -->

    <!-- BODY -->
    @RenderBody()
    <!-- /BODY -->


    <!-- FOOTER -->
    <footer class="site-footer">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-4">
                    <h3>RaptorCMS</h3>
                    <div class="post-entry-sidebar">
                        Built with ASP.NET Core and PostgeSQL, RaptorCMS aims to provide a solid foundation for your next awesome CMS project! With most of the core functionality built-in, you can focus on the specific features rather than focusing on the recurring details.
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="mb-5">
                        <h3>Quick Links</h3>
                        <ul class="list-unstyled">
                            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li><a href="@Url.Action("Index", "Blog")">Blog</a></li>
                            <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                            <li><a href="https://github.com/humzakhan/RaptorCMS">Project GitHub</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="mb-5">
                        <h3>Social</h3>
                        <ul class="list-unstyled footer-social">
                            <li><a href="@settings.GetSettingByKey(SettingsConstants.TwitterUrl).Value"><span class="fa fa-twitter"></span> Twitter</a></li>
                            <li><a href="@settings.GetSettingByKey(SettingsConstants.FacebookUrl).Value"><span class="fa fa-facebook"></span> Facebook</a></li>
                            <li><a href="@settings.GetSettingByKey(SettingsConstants.InstagramUrl).Value"><span class="fa fa-instagram"></span> Instagram</a></li>
                            <li><a href="@settings.GetSettingByKey(SettingsConstants.YoutubeUrl).Value"><span class="fa fa-youtube-play"></span> Youtube</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    Powered by RaptorCMS. Theme by <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                </div>
            </div>
        </div>
    </footer>
    <!--/ FOOTER -->

    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>

    <script src="~/themes/balita/js/jquery-3.2.1.min.js"></script>
    <script src="~/themes/balita/js/jquery-migrate-3.0.0.js"></script>
    <script src="~/themes/balita/js/popper.min.js"></script>
    <script src="~/themes/balita/js/bootstrap.min.js"></script>
    <script src="~/themes/balita/js/owl.carousel.min.js"></script>
    <script src="~/themes/balita/js/jquery.waypoints.min.js"></script>
    <script src="~/themes/balita/js/jquery.stellar.min.js"></script>
    <script src="~/themes/balita/js/main.js"></script>
    <script src="~/admin-theme/assets/js/admin.js"></script>
    <script type="text/javascript">
        function getRoute(url) {
            switch (url) {
                case 'blog':
                    return 'link-blog';
                case 'contact':
                    return 'link-contact';
                case '':
                case 'home':
                    return 'link-home';
            }
        }

        $(function () {
            var url = new URL(window.location).pathname;
            var path = url.split('/');

            var activeLink = $('#' + getRoute(path[1]));

            $('.nav-link').removeClass('active');
            activeLink.addClass('active');
        });
    </script>

    @RenderSection(name: "scripts", required: false)
    @RenderSection(name: "styles", required: false)
</body>
</html>